### PR TITLE
feat: add a rectangle and a grid of four circles

### PR DESCRIPTION
**Pull request by Mankavelda**
Hello @Sudha247 please review my first PR for rectangle and four grid circles
Screenshot from 2023-10-03 20-22-16

### CODE REVIEW

**Comment by Sudha247** [comment]
Thanks for the work @Mankavelda! Similar examples were added in #10. Would you like to propose some other example to be included? It's all right if you decide not to, this PR will still be considered as a contribution as far as outreachy is concerned.

**Comment by Mankavelda** [comment]
Thank @Sudha247 , and yes I would love to propose more examples to be included.
I think I can include:
- A Polygon
- A parallelogram
- semi circle

I will go ahead and include this with your approval @Sudha247

**Comment by Mankavelda** [comment]
> Your suggested examples sound good to me! You can go ahead. Please ensure they don't exist in the examples already.

Ok @Sudha247 , thank you

**Comment by Mankavelda** [comment]
@Sudha247 do I create an issue or I should jusst continue with this PR?

**Comment by Sudha247** [comment]
@Mankavelda apologies for my late response. It might be best to create a new PR.

**Comment by nikochiko** [comment]
@Mankavelda please create a new PR, as discussed.

I'm closing this PR now.

**Pull request closed without merging**
