### PR TITLE
Format the source code

### PR DESCRIPTION
**Pull request by joanita-51**
I've configured the automatic formatting according to the instructions outlined in issue #5

### CODE REVIEW

**Review by Sudha247 — APPROVED** [review]
Thank you @joanita-51! LGTM.

**Comment by Sudha247** [comment]
Hi, are you able to resolve the merge conflicts, please? I'll then merge it.

**Comment by joanita-51** [comment]
> Hi, are you able to resolve the merge conflicts, please? I'll then merge it.

Thank you @Sudha247 , i have been able to resolve the merge conflicts

**Comment by Sudha247** [comment]
Thanks! LGTM.

**Pull request merged**
