### PR TITLE
Added `repeat` function from original Python library

### PR DESCRIPTION
**Pull request by FayCarsons**
Since we now have higher-order transformations and complex shapes, I took the liberty of implementing the repeat function from the original Python Joy library. Additionally refactored relevant examples.

### CODE REVIEW

**Comment by FayCarsons** [comment]
@Sudha247 @nikochiko is this ready to be merged?

**Review by Sudha247 — APPROVED** [review]
Thanks! LGTM.

**Comment by Sudha247** [comment]
@FayCarsons could you resolve the merge conflicts please, and then I'll merge it.

**Comment by FayCarsons** [comment]
Done!

**Comment by Sudha247** [comment]
Thanks!

**Pull request merged**
