### PR TITLE
setting dimensions of window

### PR DESCRIPTION
**Pull request by FayCarsons**
Implemented set_dimensions function, to be used like so:
```ocaml
open Joy.Shape

let _ = 
  set_dimensions 800 800;
  init ();
  let c = circle 50 in
  render_shape c;
  close ();
  exit 0
```

### CODE REVIEW

**Review by Sudha247 — CHANGES_REQUESTED** [review]
This is a useful addition, thanks!

Could you please remove the commits from #17 as that's been merged?

**Comment by FayCarsons** [comment]
I think that should be good? Had to use some features of Git that I don't have a lot of experience with so you may want to double check, but everything looks good on my end :)

**Review by Sudha247 — APPROVED** [review]
Looks good. Thanks for the updates.

**Comment by Sudha247** [comment]
Thanks for the contribution @FayCarsons!

**Pull request merged**
