### PR TITLE
I have made some changes that can make a simple rectangle as required by issue #3

### PR DESCRIPTION
**Pull request by godplayer56**
For #3

### CODE REVIEW

**Comment by AryanGodara** [comment]
I see that you closed the previous PR (mp while resolving conflicts)
Remember it is not a good idea to leave behind PRs when conflicts occur. It piles up in the trash of the rep :( and looks bad.
Also, try to 1-2 more implementations in this. Maybe be creative and try to draw an interesting diagram :)

**Comment by godplayer56** [comment]
I am sorry, the PR closed after syncing my forked repo with the upstream. I will be more careful from now

**Comment by Sudha247** [comment]
Thanks for the PR! In addition to what @AryanGodara said, I want to add that in future please make sure nobody is working on an issue before taking it up. @nangahamandine was working on adding an illustration of a rectangle.

Also, please try to complete the issue you've already taken up. If you're stuck one of the mentors (@AryanGodara, @nikochiko or myself) will respond soon enough. We are also aware that the issues are of varying difficulties and we'll be mindful of that.

**Comment by godplayer56** [comment]
> Thanks for the PR! In addition to what @AryanGodara said, I want to add that in future please make sure nobody is working on an issue before taking it up. @nangahamandine was working on adding an illustration of a rectangle.
> 
> Also, please try to complete the issue you've already taken up. If you're stuck one of the mentors (@AryanGodara, @nikochiko or myself) will respond soon enough. We are also aware that the issues are of varying difficulties and we'll be mindful of that.

Hi @Sudha247 , I was having trouble with ocaml kernel in jupyter, I am working on it, so I tried this one first 

Is this PR ready to be merged or any changes are required😅
I'll go back to original issue after this is done

**Comment by Sudha247** [comment]
Thanks for the work. A similar rectangle example was added in #10. Could you please remove it from this PR and rebase on top of main? The rectangle is still considered as a contribution, as far as outreachy is concerned. :)

**Comment by godplayer56** [comment]
Sure @Sudha247 I'll close this PR now :smiley: 
Although I am still new to git and I'll look into how to rebase my code :sweat_smile:

**Pull request closed without merging**
