### PR TITLE
basic cairo prototype

### PR DESCRIPTION
**Pull request by FayCarsons**
Just a circle and rectangle currently, will expand to include other shapes/transformations

### CODE REVIEW

**Comment by Sudha247** [comment]
Nice work! Could you please add a screenshot of the output?

**Comment by FayCarsons** [comment]
Here's the output PNG, will try to make a habit of including them in PRs!

test2

**Comment by FayCarsons** [comment]
Here's the output from my latest commit, Rectangles, Circles, Lines, and Polygons currently work :)

cairo

**Comment by FayCarsons** [comment]
Added implementation for ellipses!

cairo

**Pull request merged**
